server:
  port: 8081
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
swagger:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
