server:
  servlet:
    context-path: /api

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_LOGIN}
    password: ${RABBIT_PASSWORD}

cors:
  allowed-origins: ${CORS_ORIGINS}

swagger:
  enabled: ${SWAGGER_ENABLED}

management:
  endpoints:
    web:
      exposure:
        include: "health"
