server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partner
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibenrate:
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: secret

management:
  endpoints:
    web:
      exposure:
        include: "health"
