server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/partner
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibenrate:
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_LOGIN}
    password: ${RABBIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health"
