server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/merchant
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
